/**
 * Traffic & data generator for the admin Lab panel.
 *
 * generateData  — seeds extra tickets/comments so the store looks lived-in.
 * generateTraffic — fires a mix of real tool calls (read, write, bad IDs,
 *                   auth-denied, rate-limit probes) so every log/counter
 *                   section fills up with interesting entries.
 */

const SUBJECTS = [
  "0 tools discovered after container restart",
  "create_ticket returns 201 but customer never receives reply",
  "mcp.json worked yesterday — 404 after new deployment",
  "describe_server shows 0 active API keys",
  "rate limiter blocking legitimate burst of queries",
  "lookup_customer returns REDACTED even with pii scope",
  "add_comment silently succeeds but comment missing in get_ticket",
  "search_tickets returns empty with status=all",
  "Container running but /health shows cwd is /tmp",
  "Cursor shows tools as unavailable — server is up",
  "Token expired mid-session without error message",
  "run_query returns wrong row count on filtered query",
  "Service account owns all tickets after bulk import",
  "Windsurf not picking up mcp.json changes on reload",
  "Bob extension reports MCP server connected but tools list empty",
];

const EMAILS = [
  "ada@example.com",
  "sam@example.com",
  "dev-team@corp.example",
  "platform-ops@corp.example",
  "maya@startup.io",
  "tyler@agency.dev",
  "noor@enterprise.ca",
];

const COMMENTS = [
  "Still seeing the same error after the fix.",
  "Confirmed — restarting the container cleared it.",
  "This is a known issue with cwd injection in Code Engine.",
  "The mcp-proxy config was pointing at the old hostname.",
  "Fixed by setting requester_email explicitly in the payload.",
  "Rate limit was triggered by the LLM retrying on empty results.",
  "Revoked old API key and issued a new one with correct scopes.",
  "Solved — the alwaysAllow list was missing the tool name.",
];

const STATUSES = ["open", "pending", "solved"];
const SERVICE_ACCOUNT = "mcp-bot@service.local";

function pick(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

function randInt(min, max) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

/**
 * Seed the store with realistic-looking tickets and comments.
 * Returns a summary of what was created.
 */
export function generateData(store, { count = 10 } = {}) {
  const created = [];
  const n = Math.min(Math.max(1, count), 40);

  for (let i = 0; i < n; i++) {
    const withEmail = Math.random() > 0.2; // 20% intentionally omit email (service-account scar)
    const { ticket } = store.createTicket({
      subject: pick(SUBJECTS),
      body: `Generated by the Admin Lab panel at ${new Date().toISOString()}. This ticket represents a realistic failure pattern.`,
      requester_email: withEmail ? pick(EMAILS) : undefined,
    });

    // Randomly resolve some
    const status = pick(STATUSES);
    if (status !== "open") ticket.status = status;

    // Add 0-2 comments
    const commentCount = randInt(0, 2);
    for (let j = 0; j < commentCount; j++) {
      store.addComment(ticket.id, {
        author: withEmail ? ticket.requester_email : SERVICE_ACCOUNT,
        body: pick(COMMENTS),
      });
    }

    created.push({ id: ticket.id, subject: ticket.subject, email: ticket.requester_email });
  }

  return { ok: true, created: created.length, tickets: created };
}

/**
 * Fire a realistic mix of MCP-style tool calls directly against store+security,
 * deliberately including errors and auth denials so every log section fills up.
 *
 * Returns a structured log of what was run and what happened.
 */
export async function generateTraffic(store, security, { rounds = 5 } = {}) {
  const log = [];
  const n = Math.min(Math.max(1, rounds), 20);

  // Anonymous principal for calls that should be denied when auth mode != off
  const anonHeaders = {};
  // Admin-scoped marker for the token env var path (stdio style)
  const adminExtra = { apiKey: process.env.MCP_API_KEY || "" };

  function record(tool, outcome, ok) {
    log.push({ tool, outcome, ok, at: new Date().toISOString() });
  }

  for (let round = 0; round < n; round++) {
    // ── 1. Happy-path read ──────────────────────────────────────────────────
    try {
      const rows = store.listTickets({ status: "open", limit: 3 });
      const allowed = security.authorizeCall("search_tickets", anonHeaders, adminExtra);
      security.recordSuccess("search_tickets", allowed.principal, { status: "open" });
      store.log({ tool: "search_tickets", count: rows.length, principal: "traffic-gen" });
      record("search_tickets", `${rows.length} open tickets`, true);
    } catch (e) {
      record("search_tickets", e.message, false);
    }

    // ── 2. Happy-path write ─────────────────────────────────────────────────
    try {
      const allowed = security.authorizeCall("create_ticket", anonHeaders, adminExtra);
      if (allowed.ok) {
        const { ticket } = store.createTicket({
          subject: pick(SUBJECTS),
          body: "Traffic generator round " + round,
          requester_email: Math.random() > 0.3 ? pick(EMAILS) : undefined,
        });
        security.recordSuccess("create_ticket", allowed.principal, { subject: ticket.subject });
        record("create_ticket", `${ticket.id} ${ticket.attribution}`, true);
      } else {
        security.recordError?.("create_ticket", allowed.principal, {}, allowed.error);
        record("create_ticket", `DENIED: ${allowed.error?.slice(0, 80)}`, false);
      }
    } catch (e) {
      record("create_ticket", e.message, false);
    }

    // ── 3. Deliberate bad ticket id — fills error log ───────────────────────
    try {
      const badId = `TCK-${randInt(9000, 9999)}`;
      const allowed = security.authorizeCall("get_ticket", anonHeaders, adminExtra);
      const ticket = allowed.ok ? store.getTicket(badId) : null;
      if (allowed.ok && !ticket) {
        security.recordError("get_ticket", allowed.principal, { ticket_id: badId }, `Ticket ${badId} does not exist`);
        record("get_ticket", `ERROR: ${badId} does not exist`, false);
      } else if (!allowed.ok) {
        record("get_ticket", `DENIED: ${allowed.error?.slice(0, 80)}`, false);
      }
    } catch (e) {
      record("get_ticket", e.message, false);
    }

    // ── 4. Deliberately bad credentials — fills denied counter ───────────────
    try {
      const badHeaders = { authorization: "Bearer mcpk_invalid_key_for_traffic_gen" };
      const result = security.authorizeCall("lookup_customer", badHeaders, {});
      if (!result.ok) {
        record("lookup_customer", `DENIED (bad cred): ${result.error?.slice(0, 80)}`, false);
      }
    } catch (e) {
      record("lookup_customer", e.message, false);
    }

    // ── 5. schema discovery + run_query ─────────────────────────────────────
    try {
      const allowed = security.authorizeCall("run_query", anonHeaders, adminExtra);
      if (allowed.ok) {
        const result = store.runQuery({ schema: "tickets", filter: { status: "open" }, limit: 5 });
        security.recordSuccess("run_query", allowed.principal, { schema: "tickets" });
        store.log({ tool: "run_query", schema: "tickets", count: result.count, principal: "traffic-gen" });
        record("run_query", `tickets schema: ${result.count} rows`, true);
      } else {
        record("run_query", `DENIED: ${allowed.error?.slice(0, 80)}`, false);
      }
    } catch (e) {
      record("run_query", e.message, false);
    }

    // ── 6. run_query with unknown schema — fills error log ───────────────────
    try {
      const allowed = security.authorizeCall("run_query", anonHeaders, adminExtra);
      if (allowed.ok) {
        const bad = store.runQuery({ schema: "orders", limit: 5 });
        security.recordError("run_query", allowed.principal, { schema: "orders" }, bad.error);
        record("run_query", `ERROR (bad schema): ${bad.error?.slice(0, 80)}`, false);
      }
    } catch (e) {
      record("run_query", e.message, false);
    }
  }

  const passed = log.filter((e) => e.ok).length;
  const failed = log.filter((e) => !e.ok).length;
  return { ok: true, rounds: n, total: log.length, passed, failed, log };
}
